repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: ruff
        name: ruff (tox)
        entry: tox -e ruff
        language: system
        pass_filenames: false

      - id: pylint
        name: pylint (tox)
        entry: tox -e pylint
        language: system
        pass_filenames: false
